{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "86382146",
   "metadata": {},
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": { \"scrolled\": true },\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"%cd /content/\\n\",\n",
    "    \"# ==============================================================\\n\",\n",
    "    \"# 1) WAN22 + ENV + TUTORIAL IMAGE + SOUND + COMFYUI\\n\",\n",
    "    \"# ==============================================================\\n\",\n",
    "    \"!wget https://huggingface.co/banhkeomath1/and/resolve/main/tutorial.png -P /content/ -q\\n\",\n",
    "    \"import base64, os, subprocess, threading, time, socket, re\\n\",\n",
    "    \"from IPython.display import Audio, Javascript, HTML, Image, display\\n\",\n",
    "    \"\\n\",\n",
    "    \"with open('/content/tutorial.png','rb') as f:\\n\",\n",
    "    \"    html_img = 'data:image/png;base64,' + base64.b64encode(f.read()).decode()\\n\",\n",
    "    \"print('✔ Tutorial encoded')\\n\",\n",
    "    \"\\n\",\n",
    "    \"!wget https://huggingface.co/banhkeomath2/wan22/resolve/main/wan22.sh -q\\n\",\n",
    "    \"!wget https://huggingface.co/banhkeomath2/wan22/resolve/main/env.txt -q\\n\",\n",
    "    \"!apt -y install aria2\\n\",\n",
    "    \"!git clone https://github.com/comfyanonymous/ComfyUI.git\\n\",\n",
    "    \"from google.colab import drive\\n\",\n",
    "    \"drive.mount('/content/drive')\\n\",\n",
    "    \"\\n\",\n",
    "    \"%cd /content/ComfyUI\\n\",\n",
    "    \"env_file = '/content/env.txt'\\n\",\n",
    "    \"with open(env_file,'r') as f:\\n\",\n",
    "    \"    for line in f:\\n\",\n",
    "    \"        if '=' in line:\\n\",\n",
    "    \"            k,v = line.strip().split('=',1)\\n\",\n",
    "    \"            os.environ[k] = v\\n\",\n",
    "    \"\\n\",\n",
    "    \"dirs = [\\n\",\n",
    "    \" os.environ.get('dif'),\\n\",\n",
    "    \" os.environ.get('cp'),\\n\",\n",
    "    \" os.environ.get('loras/wan22'),\\n\",\n",
    "    \" os.environ.get('clip'),\\n\",\n",
    "    \" os.environ.get('clipv'),\\n\",\n",
    "    \" os.environ.get('lorasf'),\\n\",\n",
    "    \" os.environ.get('ipadapter'),\\n\",\n",
    "    \" os.environ.get('loras15xl'),\\n\",\n",
    "    \" os.environ.get('cnt'),\\n\",\n",
    "    \" os.environ.get('birefnet'),\\n\",\n",
    "    \" os.environ.get('upscale'),\\n\",\n",
    "    \" os.environ.get('vae')\\n\",\n",
    "    \"]\\n\",\n",
    "    \"for d in dirs:\\n\",\n",
    "    \"    if d:\\n\",\n",
    "    \"        os.makedirs(d, exist_ok=True)\\n\",\n",
    "    \"        print('Created:', d)\\n\",\n",
    "    \"\\n\",\n",
    "    \"!hf download banhkeomath2/sound --local-dir /content/sound/\\n\",\n",
    "    \"audio_path = '/content/sound/1.mp3'\\n\",\n",
    "    \"\\n\",\n",
    "    \"def play_audio(p):\\n\",\n",
    "    \"    display(Audio(p, autoplay=True))\\n\",\n",
    "    \"    display(Javascript('document.querySelector(\\\"audio\\\").style.display=\\\"none\\\"'))\\n\",\n",
    "    \"\\n\",\n",
    "    \"play_audio(audio_path)\\n\",\n",
    "    \"\\n\",\n",
    "    \"# ==============================================================\\n\",\n",
    "    \"# 2) PINGGY TUNNEL + COMFYUI AUTO START\\n\",\n",
    "    \"# ==============================================================\\n\",\n",
    "    \"%cd /content/ComfyUI\\n\",\n",
    "    \"!pkill -f \\\"python.*main.py\\\"\\n\",\n",
    "    \"!pkill -f \\\"ssh.*pinggy\\\"\\n\",\n",
    "    \"\\n\",\n",
    "    \"COMFYUI_PORT = 8188\\n\",\n",
    "    \"PINGGY_LOCAL_PORT = '4300:localhost:4300'\\n\",\n",
    "    \"PINGGY_TOKEN = 'free.pinggy.io'\\n\",\n",
    "    \"\\n\",\n",
    "    \"tunnel_proc = None\\n\",\n",
    "    \"tunnel_url = None\\n\",\n",
    "    \"tunnel_ready = False\\n\",\n",
    "    \"\\n\",\n",
    "    \"def extract_tunnel_url(text):\\n\",\n",
    "    \"    patterns = [\\n\",\n",
    "    \"        r'https://[a-zA-Z0-9\\\\-]+\\\\.a\\\\.free\\\\.pinggy\\\\.link',\\n\",\n",
    "    \"        r'https://[a-zA-Z0-9\\\\-]+\\\\.free\\\\.pinggy\\\\.link',\\n\",\n",
    "    \"        r'https://[a-zA-Z0-9\\\\-]+\\\\.pinggy\\\\.link',\\n\",\n",
    "    \"        r'https://[a-zA-Z0-9\\\\-.]+\\\\.pinggy\\\\.[a-zA-Z]+' ,\\n\",\n",
    "    \"        r'Forwarding.*?(https://[^\\\\s]+)',\\n\",\n",
    "    \"        r'Access.*?(https://[^\\\\s]+)'\\n\",\n",
    "    \"    ]\\n\",\n",
    "    \"    for p in patterns:\\n\",\n",
    "    \"        m = re.search(p, text)\\n\",\n",
    "    \"        if m:\\n\",\n",
    "    \"            return m.group(1) if m.lastindex else m.group(0)\\n\",\n",
    "    \"    return None\\n\",\n",
    "    \"\\n\",\n",
    "    \"def start_pinggy_tunnel():\\n\",\n",
    "    \"    global tunnel_proc\\n\",\n",
    "    \"    tunnel_proc = subprocess.Popen([\\n\",\n",
    "    \"        'ssh','-p','443',f'-R0:localhost:{COMFYUI_PORT}',f'-L{PINGGY_LOCAL_PORT}',\\n\",\n",
    "    \"        '-o','StrictHostKeyChecking=no','-o','ServerAliveInterval=30',PINGGY_TOKEN\\n\",\n",
    "    \"    ], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)\\n\",\n",
    "    \"\\n\",\n",
    "    \"def monitor_pinggy():\\n\",\n",
    "    \"    global tunnel_url, tunnel_ready\\n\",\n",
    "    \"    try:\\n\",\n",
    "    \"        buf=''\\n\",\n",
    "    \"        for _ in range(50):\\n\",\n",
    "    \"            line = tunnel_proc.stdout.readline()\\n\",\n",
    "    \"            if not line:\\n\",\n",
    "    \"                continue\\n\",\n",
    "    \"            print('PINGGY:', line.strip())\\n\",\n",
    "    \"            url = extract_tunnel_url(line)\\n\",\n",
    "    \"            if url:\\n\",\n",
    "    \"                tunnel_url = url\\n\",\n",
    "    \"                tunnel_ready = True\\n\",\n",
    "    \"                print('\\\\n🌍 Public URL:', tunnel_url)\\n\",\n",
    "    \"                break\\n\",\n",
    "    \"            buf += line\\n\",\n",
    "    \"        if not tunnel_ready:\\n\",\n",
    "    \"            url = extract_tunnel_url(buf)\\n\",\n",
    "    \"            if url:\\n\",\n",
    "    \"                tunnel_url = url\\n\",\n",
    "    \"                tunnel_ready = True\\n\",\n",
    "    \"                print('\\\\n🌍 Public URL:', tunnel_url)\\n\",\n",
    "    \"    except Exception as e:\\n\",\n",
    "    \"        print('Pinggy error:', e)\\n\",\n",
    "    \"\\n\",\n",
    "    \"def iframe_thread(port):\\n\",\n",
    "    \"    print('⏳ Waiting ComfyUI...')\\n\",\n",
    "    \"    while True:\\n\",\n",
    "    \"        time.sleep(0.5)\\n\",\n",
    "    \"        s = socket.socket()\\n\",\n",
    "    \"        if s.connect_ex(('127.0.0.1',port)) == 0:\\n\",\n",
    "    \"            break\\n\",\n",
    "    \"        s.close()\\n\",\n",
    "    \"    print('✔ ComfyUI ready → creating tunnel...')\\n\",\n",
    "    \"    start_pinggy_tunnel()\\n\",\n",
    "    \"    threading.Thread(target=monitor_pinggy, daemon=True).start()\\n\",\n",
    "    \"\\n\",\n",
    "    \"threading.Thread(target=iframe_thread, daemon=True, args=(COMFYUI_PORT,)).start()\\n\",\n",
    "    \"\\n\",\n",
    "    \"!pip install -r /content/ComfyUI/requirements.txt\\n\",\n",
    "    \"!wget https://huggingface.co/banhkeomath1/and/resolve/main/ComfyUI_00005_.png -P /content/ComfyUI/input\\n\",\n",
    "    \"!pip install watchdog vtracer torchsde replicate\\n\",\n",
    "    \"!pip install sageattention==2.2.0 --no-build-isolation\\n\",\n",
    "    \"\\n\",\n",
    "    \"play_audio(audio_path)\\n\",\n",
    "    \"\\n\",\n",
    "    \"print('\\\\n🎉 INSTALL COMPLETED – READY TO RUN COMFYUI!')\\n\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": { \"display_name\": \"Python 3\", \"language\": \"python\", \"name\": \"python3\" },\n",
    "  \"language_info\": { \"name\": \"python\", \"version\": \"3.10\" }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
